---
title: "game_data_exploring"
author: "Shreya"
date: "September 11, 2017"
output: html_document
---

```{r}
getwd()
```

```{r}
data <-read.csv("C:/Users/Shreya/Documents/GITHUB/class-activity_game_data/game.data.csv", sep=",")
names(data)
```

```{r}
hist(data$avatar.complexity, breaks=50, col="hotpink4")
```

```{r}
hist(data$levels, col="olivedrab")

#or 
#hist(data$levels, breaks=10, col="olivedrab")
```

```{r}
hist(data$skill.tree, breaks=10, col="royalblue4")
```

```{r}
hist(data$login, breaks=25, col="sandybrown")
```

```{r}
hist(data$score, breaks=25, col="tomato3")
```

```{r}
#to view what are the trends in the data
data1 <- data[-c(1)]
plot(data1, col="royalblue4")
```

```{r}
data2 <- data1[-c(6)]
plot(data2, col="darkgreen")
```

```{r}

#install.packages("psych", dependencies = TRUE) if there is an error
install.packages("psych")
library("psych")
pairs.panels(data[c(1:7)], gap = 0)
```

as expected id and degree.centrality.rank are not that significantly related to the other variables, so we make a pair panels without them.
```{r}
pairs.panels(data[c(2:6)], gap = 0)
```

Some insights from this graph
- # of logins is positively corelated to avatar.complexity by .79

- score increases with levels or levels increase with score by a corelation of .68
- skill tree increases with score at .40




#PCA
```{r}
data1 <- data[-c(1)]
data1 <- data1[-c(6)]
View(data1)
data1 <- scale(data1, center = TRUE)
pca <- prcomp(data1, scale = TRUE)
pca$sdev
pca$sdev^2
summary(pca)
plot(pca, type = "lines")
data2 <- as.data.frame(pca$x)
View(data2)
```


#Regression
```{r}
reg1 <- lm(skill.tree ~ login + score + levels + avatar.complexity, data = data)
summary(reg1)
```

```{r}
reg2 <- lm(skill.tree ~ score + login + avatar.complexity, data = data)
summary(reg2)
```

```{r}
reg2 <- lm(skill.tree ~ score + login, data = data)
summary(reg2)
```


